;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        forward-sentence
        haskell-mode-contextual-space
        kill-region
        live-paredit-delete-horizontal-space
        live-paredit-forward-kill-sexp
        paredit-backward-down
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-curly
        paredit-open-round
        paredit-raise-sexp
        paredit-semicolon
        scala-electric-brace
        sgml-slash
        win-switch-exit
        ))

(setq mc/cmds-to-run-once
      '(
        cider-load-file
        ido-switch-buffer
        paredit-open-square
        smex
        win-switch-dispatch
        win-switch-exit-and-redo
        ))
